server:
  port: 8081

spring:
  profiles:
    active: dev

-----------


spring:
  profiles: dev
  datasource:
    url: jdbc:sqlserver://168.232.165.32;databaseName=TRANSCAR
    username: sa
    password: Louisse98
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC


app.jwtSecret: TransportesScaramutti
app.jwtExpirationInMs: 604800000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG